### ISSUE TITLE
Order book resync issue and recover ideas

### ISSUE THREAD

**Issue by osnwt** [evilive3000/poloniex-orderbook#9] opened 2017-02-06 22:50 UTC
On some lazy markets like BTC_SC the order book quite often stalls with updates. Push messages contain actual data for a given rate but orderbook is not updated as it should for many seconds or even minutes.

The reason is that Poloniex may drop a sequence number in their push stream, and in case of low update rate (a message in few seconds or even few messages per minute) it may last long until buffer gets 25 messages to be reset. I checked the original push stream using clean Polo API and found that yes, it sometimes may skip a seq number completely. So it is not a module issue. But the issue is how to recover from it as fast as possible.

AFAIK, the push stream uses TCP connection that should not reorder messages (unlike few https API calls that often return nonce errors due to packet reordering). I know that Poloniex suggests to apply messages in order, but in this case missed message just stops the processing.

I see two ways of resolving the issue.

- Do you really think or observed that the API returns orderbook messages in wrong order? I didn't. So I think that 25 messages in a buffer is a lot, and maybe 1 or 2 should be enough. Maybe we may send this optional limit to constructor.

- Maybe we could have some reasonable timeout for non-empty buffer state. That is, if a message in the stream was reordered, we may expect it to receive soon. If we didn't receive it, say, in a second, it should be considered lost, and buffer should be reset.

As for me, I changed 25 to 1 and have good results for that market. Maybe another investigation should be conducted before changes. But unfortunately at the moment update freeze could occur quite often on such markets.

**Comment by evilive3000** [comment] 2017-02-07 07:26
Oh, you've made a very deep analysis, thank you.

About wrong seq-numbers in push events I can say "yes", I definitely met wrong sequences. Maybe it's depend on how frequently events come, and less frequent markets produces less mistakes. 
I will rethink the "25-messages in buffer" strategy, and I agree with you we can do it more adjustable.

ps. sorry for delays, unfortunately I can't spend a lot time for the lib now, but I promise to fix accumulated issues.

**Comment by evilive3000** [comment] 2017-02-07 08:12
I just tested the lib a bit and see that it doesn't work properly now.
Something changed in push events and now it's seq-number does not increasing by 1. 
```
[250931214, 250931219, 250931225, 250931226, 
250931227, 250931228, 250931229, 250931237, 
250931238, 250931241, 250931244, 250931245, 
250931246, 250931260, 250931262, 250931279, 
250931280, 250931283, 250931288, 250931289, 
250931290, 250931292, 250931293, 250931297, 
250931301, 250931302, 250931303, 250931304]
```
Now it can skips big parts, so the orderbook just fill buffer and restarts every 25 events.
So a quick fix would be refusing to use buffer and do full reset each time wrong seq number comes.

**Comment by osnwt** [comment] 2017-02-07 13:43
I would suggest to provide 2 optional parameters to constructor call after currency pair (= means defaults):
- **bufferLimit = 10** - the size of buffer after processing that results in reset if greater than;
- **bufferTimeout = 1000** - the timeout in ms for waiting for right seq number. If after buffer processing we still have bufferSize > bufferLimit AND time since previous buffer processing is greater than this (1 second by default) - reset the orderbook.

I think it will completely fix the issue. We can't know if missing seq number is lost forever or it isn't arrived yet. So we wait up to bufferLimit out-of-order msgs, but will reset after bufferTimeout ms if still not in sync. With suggested defaults it will use buffer with depth 10 (or maybe even 0 should be allowed - do not use buffer at all), but still will reset in a second if something went wrong.

Both fixes seem to be trivial. I can do it for myself, but I think it should be fixed in the official repo.

**Comment by evilive3000** [comment] 2017-02-08 11:19
spent few hours and found something interesting.
Originally I use `autobahn.js` for reading data through WAMP protocol, which connects to `wss://api.poloniex.com`.
Also I found in the poloniex's frontend code that they use alternative ws connection to `wss://api2.poloniex.com`. I tried to do same and here what I got:

|ws (wss://api2) |autobahn (wss://api)|
|-|-|
251845814 | 251845814
251845815 | 251845815
251845816 | 
251845817 | 251845817
251845818 | 251845818
--------------- | **251845816**
251845819 | 251845819
251845820 | 251845820
251845821 | 251845821
251845822 | 251845822
251845823 | 251845823
251845824 | 251845824
251845825 | 251845825
251845826 | 251845826
251845827 | 251845827
251845828 | 251845828
251845829 | 251845829
251845830 | 251845830
251845831 | 
251845832 | 251845832
251845833 | 251845833
251845834 | 251845834
251845835 | 251845835
251845836 | 251845836
251845837 | 251845837

so the problem may be caused by `autobahn.js` lib or `url`. I think it's first.

**Comment by evilive3000** [comment] 2017-02-08 11:23
I'm going to rewrite the lib without `autobahn`. I'll fix buffer and precision issues.

**Comment by osnwt** [comment] 2017-02-08 15:21
Very interesting. Can't say about reordering, but missing 251845831 in the second column is exactly what I observed. Maybe try to swap api and api2 first to see if it was really caused by autobahn? If yes, that's very sad since a lot of projects use it.

**Comment by osnwt** [comment] 2017-02-27 11:08
Just tried to repeat the issue with alternative wamp implementation Wampy (npm install wampy) and got exactly the same result with both autobahn and wampy subscriptions: missing seq number.

I start thinking it is an issue with API/publisher, not with autobahn as such. Maybe api2 works better, but wampy disconnects right after connect (maybe some preconditions exist to connect via api2, I did not look deeper).

**Comment by evilive3000** [comment] 2017-03-21 09:50
I pushed a new version. It's incompatible with previous. So the issue may not be relevant now. I'm closing the issue. If there some new problems just create a new issue.

**Closed as completed by evilive3000** 2017-03-21 09:50 UTC

**Comment by osnwt** [comment] 2017-03-21 09:58
Agreed. No sense to use WAMP API while WS version works just great.
